# File Naming

*Last updated `r Sys.Date()`*

File naming isn’t exactly fun, but it is crucial for organizing, describing, and managing all kinds of work, especially research. So, let’s talk about the file naming conventions that you will be expected to use while at UBCO.

We'll start with the rules, we'll then break these rules down and explain the processes behind them.

## Quick Reference

* File names should only contain letters in the English alphabet, numbers from 1-9, dashes `-`, and underscores `_`.
* Do not use spaces or special characters, including <code># % & < > : \" / \ | ? * { } $ ! \' @ + ` =</code>
* File names should be broken down into components that are separated by underscores `_`.
* If more than one word is needed in each component, these are separated by dashes `-`.
* All files should start with your last name and all other components should be meaningful (read on for what it means for a file name to be meaningful!)

There are four variations on how these guidelines are implemented depending on what your file contains.

### Lab reports and manuscripts

**Format** LastName_Project_File-contents_Version.file-type

**Example** <code>Pither_BIOL116RProject_Manuscript_V0.docx</code>

### Figures and plots

**Format** LastName_Project_Figure-title_Version.file-type

**Example** <code>Pither_BIOL116RProject_Figure-freq-plot_V1.png</code>

### Analysis

**Format** LastName_Project_Analysis_Version.file-type

**Example** <code>Pither_BIOL116RProject_Analysis_V0.xlsx</code>

### Data

**Format** LastName_Date_Project_Data-file-description.file-type

**Example** <code>Pither_20210921_BIOL116RProject_Data.csv</code>

## What's in a name

File names need to achieve two primary goals, they need to make sense to a human reading them and they need to be constructed in a way that allows a computer to parse or process them. That is, file names should be **human interpretable** and **machine readable**. How do we achieve this?

### Human interpretable {-}

To be human interpretable, a file name needs to be meaningful. To do this, it needs to convey some basic information to a person reading it. We do this by integrating <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Metadata">metadata</a> into the file name. The metadata elements we include are:

* Who created the file
* The date on which it was created
* The project to which it is connected
* The nature of the contents of the file
* If it's been modified
* The type or format of the file

That is, we should be able to look at a file and tell, *who* created it, *when* it was created, *what* it is related to, *what* is inside of it, if it has been *updated*, and what *application* I should expect to be able to open it with. As we'll see shortly, we don't always include a date, and we don't always include information about modifying a file.

All said, that's a fair bit of information to hold in a file name!

### Machine readable {-}

What does it mean for a file name to be machine readable or machine interpretable? It means building our file names in such a way that we can easily organize them so that they can be sorted by an application and in a way that makes sense to us. It also means building our names according to set patterns, which can then be parsed along known <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Delimiters">delimiters</a>. Lastly, it means building our names in such a way that if we move them from one computer to another, from one application to another, or from one operating system to another, the files remain interpretable in exactly the same way.

How do we do this? We avoid special characters and follow conventions.

#### Special characters {-}

Special characters are all characters **except**:

* Any character that is a part of the English alphabet
* Numbers from `0 - 9`
* Dashes `-`
* Underscores `_`

This means that a space \" \" is a special character, which means that your file names should not have spaces.

When operating in a multi-lingual or non-English environment, this can prove problematic, but it is an unfortunate legacy of the development of computer standards that has yet to be fully resolved.

#### Conventions {-}

Convention has file naming proceed in the following order, with each element separated by an underscore `_`, and words within an element joined with a dash `-`. The file type is generally added with a period `.` and is usually automatically generated when an application creates a file.

| Element-1 | \_Element-2 | \_Element-3 | \_Element-4     | _Element-5 | .Element-5 |
| :--------- | :----------- | :----------- | :--------------- | :---------- | :---------- |
| Last-Name | _Date       | \_Project   | \_File-Contents | \_Version  | .File-type |

#### Dates {-}

Dates should be written in the following format `yyyymmdd`. They should contain no spaces, no dashes, no words, just 8 numbers. Months and Days that are from 1 - 9 should be led by a 0. For example, January 23, 2020, should be written **20200123**. When written this way, your computer will always sort your files from the earliest date to the latest date.

Keeping track of dates is especially important for data because the date on which your data was collected has direct relevance. Dates are less important for things like figures because they are derived from previously dated data.

#### Versions {-}

Version tracking is achieved in file naming by adding <code>_V*n*</code> where *n* is the version number. With each major change, we increase *n* by 1. So version 1 would read <code>_V1</code>, and when updated, it would read <code>_V2</code>.

Versions are very important for things like manuscripts and interpretations of data, such as figures and other visualizations, which we will continue to change and modify throughout a project. Data, however, while it has a collection date, should not be modified, and should not then be versioned.

## An example

So what does this look like?

Say you're in BIOL 116 and you're working on your research project. Your research project involves:

* Preparing the beginning of a manuscript that states your research question, <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Hypothesis">hypothesis</a>, and proposed methods.
* Conducting your experiment and recording your data. This process might span more than one day.
* Updating your manuscript, describing any changes that were made to your methods.
* Organizing the results of your experiment and interpreting and visualizing your data.
* Updating your manuscript to include your results and your interpretation of these results, including a visual interpretation.
* Completing your manuscript by discussing the importance of and / or limitations of the experiment, and finally producing a conclusion.

In this scenario, we have **1 project**, **1 manuscript**, **1 dataset**, and at least **1 figure**. In addition, our dataset is constructed from data collected over several days, and our manuscript is revised 3 times before final submission.

So, first we will come up with a project name, and then we will **date our data** and **version our figures and manuscript**. And we'll see how this evolves over the course of several days.

#### Day 1 {-}

We create the following file:

<code>Pither_BIOL116RProject_Lab-report_V0.docx</code>

This is our manuscript, so it will get a version, but no date. Looking at it, we quickly see that this is a lab report (Lab-report), authored by someone with the last name Pither (Pither) associated with a BIOL 116 Research Project (BIOL116RProject), that it has only just been created (V0), and that I should expect it to open in Microsoft Word (docx).

Let's imagine that I will put my research question, hypothesis, and methods in this document and submit it.

#### Day 2 {-}

Today, I conducted the first part of our experiment and collected some data. Now we have the following files:

```
Pither_20210921_BIOL116RProject_ph-data.csv
Pither_BIOL116RProject_Lab-report_V0.docx
```

We have not changed our manuscript, so there's no change to the name. However, we have collected some data. We can easily see who collected this data (Pither), when it was collected (September 21, 2021), that it's connected to the BIOL 116 Research Project (BIOL116RProject), and that it's data related to PH exposure. Lastly, it is formatted as comma separated values (csv), which can be opened by any spreadsheet program or text editor.

#### Day 3-5 {-}

I continue to collect data over the next several days, and here is what my files now look like:

```
Pither_20210921_BIOL116RProject_ph-data.csv
Pither_20210922_BIOL116RProject_ph-data.csv
Pither_20210923_BIOL116RProject_ph-data.csv
Pither_20210924_BIOL116RProject_ph-data.csv
Pither_BIOL116RProject_Lab-report_V0.docx
```

Again, we have not changed our manuscript, so there's no change to the name. However, we have collected some more data related to PH. We have one file for each day, organized from the earliest day of collection to the most recent.

#### Day 6 {-}

Today, I did two things. I have no more data to collect, so I updated my manuscript to include any modifications made to my original methods section, I then submitted this. I also started to analyze my data; to do this, I merged all my data into a single file for analysis. Now my files look like this:

```
Pither_20210921_BIOL116RProject_ph-data.csv
Pither_20210922_BIOL116RProject_ph-data.csv
Pither_20210923_BIOL116RProject_ph-data.csv
Pither_20210924_BIOL116RProject_ph-data.csv
Pither_BIOL116RProject_Analysis_V0.xlsx
Pither_BIOL116RProject_Lab-report_V0.docx
Pither_BIOL116RProject_Lab-report_V1.docx
```

At this stage, I have my data collated into a document where I can work on it without impacting the original data. We can see that I have done this in Excel (xlsx), and that I should expect to be able to open this file in Excel. I also now have a V1 of my manuscript, as I have now added a new section to it; when submitting it, my TA knows that the file with V1 should have this updated section.

#### Day 7 {-}

Today, I built two visualizations using the data in my analysis document, one <a href="https://ubco-biology.github.io/Procedures-and-Guidelines/glossary#Linear-regression">linear regression</a> and one bar plot of frequency counts; I save these as images to insert into my manuscript. I then updated my manuscript to include my results and these two figures and submitted V2 of my manuscript. Now my files look like this: 

```
Pither_20210921_BIOL116RProject_ph-data.csv
Pither_20210922_BIOL116RProject_ph-data.csv
Pither_20210923_BIOL116RProject_ph-data.csv
Pither_20210924_BIOL116RProject_ph-data.csv
Pither_BIOL116RProject_Analysis_V0.xlsx
Pither_BIOL116RProject_Figure-freq-plot_V0.png
Pither_BIOL116RProject_Figure-linear-reg_V0.png
Pither_BIOL116RProject_Lab-report_V0.docx
Pither_BIOL116RProject_Lab-report_V1.docx
Pither_BIOL116RProject_Lab-report_V2.docx
```

We can start to see the advantage here of naming conventions. I can easily see which files are which, what they contain, and what their timeline of development is. Also, my computer easily sorts these into meaningful categories - my data is grouped together, sorted by date. My analyses, figures, and manuscripts are all respectively grouped and sorted by version.

#### Day 8 {-}

I got feedback that my linear regression model had an error in it. So I fixed this today, added the new figure into my manuscript, and wrote the discussion and conclusion sections. I'm now ready to submit. Here is what my files look like now (I will be submitting V3 of my manuscript):

```
Pither_20210921_BIOL116RProject_ph-data.csv
Pither_20210922_BIOL116RProject_ph-data.csv
Pither_20210923_BIOL116RProject_ph-data.csv
Pither_20210924_BIOL116RProject_ph-data.csv
Pither_BIOL116RProject_Analysis_V0.xlsx
Pither_BIOL116RProject_Figure-freq-plot_V0.png
Pither_BIOL116RProject_Figure-linear-reg_V0.png
Pither_BIOL116RProject_Figure-linear-reg_V1.png
Pither_BIOL116RProject_Lab-report_V0.docx
Pither_BIOL116RProject_Lab-report_V1.docx
Pither_BIOL116RProject_Lab-report_V2.docx
Pither_BIOL116RProject_Lab-report_V3.docx
```