# Directories

*Last updated `r Sys.Date()`*

Directories are just folders; we'll use the terms interchangeably. All of the files on your computer are organized around folders. In some respects, this means that your computer is synonymous with a filing cabinet; you open it up and there are a bunch of folders holding files and sub-folders. Following this analogy, if you were to open your computer--and you were on a Mac--you'd see 16 folders, including the following:

```
Applications/
Users/
home/
Library/
Volumes/
System/
bin/
usr/
```

There's a very good chance you've never seen any of these folders. We call this the root of your file system; these folders don't sit inside of any other folders, they only hold other folders and files.

The folder called `Users` holds all of the files that you create on your computer. In fact, there is a folder in there named after the user name that you use to log into your computer with. And within that a series of folders that you should be fairly familiar with including a `Downloads\` and `Documents\` folder. It also includes a `Desktop\` folder--your desktop is just another folder containing files, but one that has special status in terms of how those files are shown to you--ie, on your desktop when you start up your computer.

<div class = "note">
When writing about directories, directory names are frequently followed by a slash--`/`--to differentiate them from files.
</div>

If we were to represent this graphically--as a hierarchy--we'd have something like this:

```
├── Users/
│   ├── yourUserName/
│   │   ├── Downloads/
│   │   ├── Documents/
│   │   ├── Desktop/
```

## Working directory

Your **working directory** is the folder you're working in or the folder that holds the file that you have open.

Let's say you create a folder on your `Desktop` called `BIOL-125/` to hold all of your coursework for this class. And in it you have another folder for your research project--`Research-Project/`--in which you have a Word file for keeping notes--`biol-125_research-project_notes.docx`.

A directory map would now look something like the following:

```
├── Users/
│   ├── yourUserName/
│   │   ├── Downloads/
│   │   ├── Documents/
│   │   ├── Desktop/
│   │   |   ├── BIOL-125
│   │   |   |   ├── Research-Project/
│   │   |   |   |     ├── biol-125_research-project_notes.docx
```

When you open your `Research_project` folder, we call this your working directory--the directory that holds the files that you are currently working with, or that you currently have access to. If you clicked on your `Desktop`, your working directory would switch to your `Desktop`, since we know that your `Desktop` is just another folder.

This has implications for how the applications that you work with access the files on your computer. If you opened your file `biol-125_research-project_notes.docx`, `Research-Project` would not only be your working directory, it would be Microsoft Word's working directory for that file. With `biol-125_research-project_notes.docx` open, if you went to `File > Open...` in Word, it would prompt you to open a file in the directory `Research-Project`.

Generally, in day to day life, we don't need to worry about things like working directories. When we conduct research though, and we use tools like `R`, working directories--and knowing where directories and files are in relation to the directory that you are currently in--have significant implications for how things work and for computational reproducibility.

In the next section, we'll look at common directory structures used to organize research. For the moment, we'll assume that you have a research project and that associated with that research project you have data and that you're analyzing that data, and that you're using two different folders to hold the files associated with these activities. So a map something like the following:

```
├── Users/
│   ├── yourUserName/
│   │   ├── Downloads/
│   │   ├── Documents/
│   │   ├── Desktop/
│   │   |   ├── BIOL-125
│   │   |   |   ├── Research-Project/
│   │   |   |   |     ├── Data/
│   │   |   |   |     ├── Analysis/
│   │   |   |   |     ├── biol-125_research-project_notes.docx
```

If you have a file in your `Analysis/` folder open, `Analysis/` is your working directory. If this file needs to access a file with data in your `Data/` directory, you need to be explicit about where this file lives--it lives up one level in the hierarchy in another folder called `Data/`.

## Relative and Absolute Paths

When talking about file locations, a path tells us where a file lives within a directory structure. Paths can be absolute or relative.

### Absolute paths

Absolute paths tell us the location of a file relative to the whole directory structure. Using the example above, the absolute path of `biol-125_research-project_notes.docx` is `Users/youUserName/Desktop/BIOL-125/Research-Project/`.

### Relative paths

Relative paths on the other hand tell us the location of a file relative a working directory. So, if you're working directory is your Desktop, the relative path of `biol-125_research-project_notes.docx` is `BIOL-125/Research-Project`.