# (PART\*) Glossary {-}

# Glossary

### A {-}

<a id="A-priori-hypothesis">**A priori hypothesis:**</a> Hypothesis that is generated before the research study takes place. Presenting the hypothesis before the study takes place helps in avoiding replacing the hypothesis later with one that fits the data better aka hypothesizing after the fact (HARKing). 

### B {-}

<a id="Bias">**Bias:**</a> Error is introduced and false conclusions might be drawn because our sample doesn't meet established standards for faithful representation of our population of interest.

<a id="Burden-of-proof">**Burden of proof:**</a> The obligation that when a causal link is suggested that evidence to support this link must be presented. This can be accomplished through independent replication of studies where if they demonstrate the same conclusions it reinforces the validity of the causal link between those variables. 

### C {-}

<a id="Clinical-trials">**Clinical trials:**</a> Experiments that involve i) human participants who are assigned in advance to a group that receives a particular treatment designed to produce a biomedical or behavioural result and ii) evaluation of the effect of the treatments (NIH, 2017)

<a id="Citizen-science">**Citizen science:**</a> When members of the public engage in the research process. Often involving collaboration with researchers. 

<a id="Confirmatory-research">**Confirmatory research:**</a> Researchers used a well designed experiment to test the validity of predetermined hypotheses that can be disproved. 

<a id="Critical-analysis">**Critical analysis:**</a> Careful examination and evaluation of all parts of a research article including consideration of the study’s strengths and weaknesses as they relate to study design, implementation, data collection, data analysis, and interpretation. 

### D {-}

<a id="Descriptive-statistics">**Descriptive statistics:**</a> A number used to summarize or describe a given data set or sample. Examples include mean, median, mode, standard deviation, and interquartile range. 

<a id="Diversity">**Diversity:**</a> The practice or quality of having individuals who vary in terms of social class, ethnic background, sexual orientation, gender, religion, ability, etc. 

### E {-}

<a id="Effect-size">**Effect size:**</a> A measure of the degree of association between one variable and another, or in experimental contexts, of the impact of one variable on another.

<a id="Equity">**Equity:**</a> The practice of treating all segments of society in such a manner that everyone has a similar chance of achieving a given outcome. Some individuals and groups may need more or different support than others to achieve that outcome. “Equality” , in contrast, refers to the practice of providing identical support and opportunities to all.

<a id="Exploratory-research">**Exploratory research:**</a> Research that is performed to gain a better understanding of an existing problem. For example, it might give rise to hypotheses that can then be tested through confirmatory research. 

### F {-}

<a id="File-and-data-management">**File and data management:**</a> Refers to practices used to collect, generate, and store data and files throughout the research process. Researchers should document what type of data they have collected, the methods used, and any relevant context. Files and data should be stored such that they are organized, accessible, and interpretable by both the researcher and others. 

<a id="HARKing">**HARKing:**</a> A form of questionable research practices where the researcher changes their hypothesis after the study is conducted so that the hypothesis better fits the data. In other words, the researcher suggests that this post hoc (after the fact) hypothesis was formed a priori. This has a number of implications including: “harming the progress of science by preventing the research community from identifying already falsified hypotheses, contributes to the replication crisis, and it increases the probability that the findings are not reproducible or generalizable in the population of interest”. ([UCDavis Health, n.d.](https://health.ucdavis.edu/ctsc/area/Resource_Library/documents/HARKing_0Jan2021.pdf))

<a id="Hypothesis">**Hypothesis:**</a> A proposed explanation for an observed phenomenon. Often structured in an “If… then… because…” format. Hypotheses must be present a priori, be falsifiable, and measurable. 

<a id="Hypothesis-testing">**Hypothesis testing:**</a> Typically involves setting a null and alternative hypothesis and performing an appropriate statistical analysis to test those hypotheses. Often used in confirmatory research. 

<a id="Inclusion">**Inclusion:**</a>  The philosophy or practice of considering individuals from diverse backgrounds in relation to the community, organization, or society, and ensuring that they feel that they belong, supporting them in giving their best efforts, and giving them equal opportunities to advance and participate in decision-making.

<a id="Literature-review">**Literature review:**</a> A review of scholarly sources related to a specific research question or topic. Involves recording a list of research studies consulted, how they were found, and the strengths, limitations, and weaknesses of each. 

<a id="Metadata">**Metadata:**</a> Data that provides information about other data.

<a id="Open-notebooks">**Open notebooks:**</a> Involves i) publishing or linking to data on an online platform before results are published in a peer-reviewed journal; ii) making information about the methodology and equipment used in a study publicly available; iii) openly discussing both positive and negative results in real time, as they are obtained.

<a id="Open-science">**Open science:**</a> A movement and set of practices intended to combat the replication crisis, QRPs, and style trumping substance by making all parts of the scientific research process transparent and accessible, allowing for a critical review of how a study was conducted, ultimately enabling that study to be independently replicated. It also involves changing scientific culture to reward not just novel findings, but also the many other aspects of conducting good scientific research.

<a id="Participatory-research">**Participatory research:**</a> Turns the relationship between researcher and subject into a partnership, where both contribute to the research question, methods, and outcomes.

<a id="Peer-review">**Peer review:**</a> Peers of the author critically review the author’s study. Traditionally peer review focused on the evaluation of studies prior to publication, however open science practices suggest additional peer review at the study design stage prior to implementation. This ensures the study design meets accepted quality standards before it is conducted. 

<a id="Questionable-research-practices">**Questionable research practices:**</a> A grey area of scientific practice in which researchers do not engage in outright misconduct such as fraud or plagiarism, but may unwittingly break rules of acceptable scientific practice in the pursuit of novel and promising results.

<a id="R">**R:**</a> a programming language and free software for statistical computing. When used throughout the research process, it allows for openness in the research workflow and computational reproducibility. 

<a id="Replication">**Replication:**</a> Thorough repetition of a study, using the same methods but different data.

<a id="Replication-crisis">**Replication crisis**</a>: Many studies cannot be competently analyzed or replicated. This is because critical information about them—design, data, methods, lab notes, analyses and code—may not be made available, or may be poorly communicated. This problem is escalated further because new and original findings are considered more exciting than re-testing or replicating previously conducted studies. 

<a id="Reproducibility">**Reproducibility:**</a> \"Obtaining consistent results using the same input data; computational steps, methods, and code; and conditions of analysis\". 

<a id="Research-transparency">**Research transparency:**</a> The quality or practice of revealing all inputs and outputs of the research process clearly, as well as making evident the exact reasoning and process used in coming to a decision or taking actions in research, in such a way that the study can be replicated. As well, transparency means taking care to disclose important information in a respectful and responsible fashion.

<a id="Research-lifecycle">**Research lifecycle:**</a> The traditional research cycle involves five stages, 1) develop idea, 2) design study, 3) collect and analyze data, 4) write report, and 5) publish report. Traditionally, peer review has been conducted after writing the report and prior to publication. However, open science proposes revising the research life cycle by introducing an additional peer review after the study design stage. 

<a id="Scientific-method">**Scientific method:**</a> An empirical method for acquiring knowledge which includes making an observation, asking a question, forming a hypothesis, making a prediction based on the hypothesis, and testing the prediction. 

<a id="Scientific-integrity">**Scientific integrity:**</a> \"The condition resulting from adherence to professional values and practices when conducting, reporting, and applying the results of scientific activities that ensures objectivity, clarity, and reproducibility, and that provides insulation from bias, fabrication, falsification, plagiarism, inappropriate influence, political interference, censorship, and inadequate procedural and information security.\" ([USDA, n.d.](https://www.usda.gov/our-agency/staff-offices/office-chief-scientist-ocs/scientific-integrity-and-research-misconduct))

<a id="Statistical-analysis">**Statistical analysis:**</a> Involves collecting, organizing, exploring, interpreting, and presenting data to uncover patterns or trends in the data. Involves using statistics to describe the study sample and use that sample to make inferences about the population of interest. 

<a id="Statistical-significance">**Statistical significance:**</a> If a result is determined to have statistical significance it means that the result from the study is not likely to have occurred randomly or by chance. In other words, the result is likely to be caused by something other than chance. The significance level (𝝰) is set by the researcher in advance of the study being performed. Often 𝝰 is set to 0.05, which indicates a 5% chance of making the wrong decision and determining that the null hypothesis is false when it is in fact true. 

<a id="Study-power-(aka-statistical-power)">**Study power (aka statistical power):**</a> The probability that a random sample taken from a population will lead to rejection of the study’s null hypothesis if that null hypothesis is in fact false. That is, power is a measure of how reliable a study is as a test for its hypothesis; power is positively influenced by things like large sample sizes and relationships characterized by large effect sizes.

<a id="Version-control">**Version control:**</a> Saving changes to files while retaining the changes on all previous versions of the file. This practice contributes to transparency and openness in science. 

