# APA Citations

This is a brief overview of the 7th edition of APA for quick reference. For a more in depth review, please consult [the library's APA Citation Guide](https://guides.library.ubc.ca/apacitationstyle). For the full APA manual, please consul the [Publication Manual of the American Psychological Association](http://resolve.library.ubc.ca/cgi-bin/catsearch?bid=10057275), available through the library.

Additional resources you may wish to consult include:

* The [APA Style Blog](https://apastyle.apa.org/blog/) - great for searching for examples not listed in the 7th edition
* Purdue OWL's [website](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html) for still more examples

## In-text Citations

Always appear right after the content you are summarizing, paraphrasing, or quoting. The format is as follows:

**Summarizing or Paraphrasing**

- (Author, YYYY)

**Quoting**

- (Author, YYYY, p. #) <code>1 page</code>
- (Author, YYYY, pp. ##-##) <code>Multiple pages</code>

### Narrative vs Parenthetical {-}

If you mention the author or authors in text, you do not need to include this information in the brackets, \"()\". This is called a narrative citation.

**Narrative in-text citation:** Raimi (2018) outlines the risks and benefits of fracking through an economic analysis and energy security benefits.

The alternative is called a parenthetical citation.

**Parenthetical in-text citation:** Several benefits and risks can be identified in the implementation of fracking for oil  extraction. Considerations include regulation, water pollution, tremors  etc. (Raimi, 2018).

### Quick Format Guide {-}

| # of Authors | Narrative Example | Parenthetical Example |
| --- | --- | --- |
| 1 | Bradley (2017) | (Bradley, 2017) |
| 2 | Janmaat and Rahimova (2018) | (Janmaat & Rahimova, 2018) |
| 3 or more | Mei et al. (2018) | (Mei et al., 2018) |

## Reference List

**NOTE**

* Every source used in your in-text citations needs to be listed as  part of your reference list, in alphabetical order by author(s)' last  names.
* The word **References** should appear at the top of your reference list, and it should be centred and bolded on the page
* Titles should be written in sentence case, that is, capitalize the  first word and only subsequent proper nouns. If the title is broken up  by a colon (:), capitalize the first word after the colon.
* List all authors in the order that they appear in the source.

### Journal article with a DOI (1-2 authors) {-}

List all authors in reference list and in-text citations.

Janmaat, J., & Rahimova, N. (2018). Managing drought risk in the Okanagan: A roll for dry-year option contracts? *Canadian Public Policy*, *44*(2), 112-125. https://doi.org/10.3138/cpp.2017-003

### Journal article with a DOI (3-20 authors) {-}

List all authors in the reference list and only first author in the in-text citations.

Mei, Y., Yu, K., Lo, J. C. Y., Takeuchi, L. E., Hadjesfandiari, N.,  Yazdani-Ahmadabadi, H., Brooks, D. E., Lange, D., & Kizhakkedathu,  J. N. (2018). Polymer-nanoparticle interaction as a design principle in  the development of a durable ultrathin universal binary antibiofilm  coating with long-term activity. *ACS Nano*, *12*(12), 11881-11891. https://doi.org/10.1021/acsnano.8b05512
