--- 
title: "Procedures and Guidelines"
author: "Clerissa Copeland, Jason Pither, and Mathew Vis-Dunbar"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "Recommended guidelines for producing and formatting research outputs, including data, figures, and reports."
---

# Welcome {-}

The procedures and guidelines articulated in this document represent accepted standards for the conduct and presentation of student works in the Biology undergraduate curriculum at UBC Okanagan.

These guidelines are modeled on best practices in the life sciences and where necessary, adapted specifically for the biological sciences and student engagement in learning and research.

**For Students** These are guidelines only. You may be asked to adhere to them directly as part of your coursework or you may be asked to work with a specific implementation of what is suggested here.

**For Instructors** Any concerns or omissions from these procedures and guidelines can be forwarded to Jason Pither (jason.pither@ubc.ca) or Mathew Vis-Dunbar (mathew.vis-dunbar@ubc.ca)

**NOTE** This is a living document. Expect that content will be added over time and adapted as needs and circumstances change.

## Copyright {-}

This work is licenced under the Creative Commons [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

Please use the following for citing this document

Copeland, C., Pither, J., Vis-Dunbar, M. (2021). *Procedures and Guidelines*. [https://ubco-biology.github.io/Procedures-and-Guidelines/](https://ubco-biology.github.io/Procedures-and-Guidelines/)

All source files are available at [https://github.com/ubco-biology/Procedures-and-Guidelines](https://github.com/ubco-biology/Procedures-and-Guidelines).

## Why Procedures and Guidelines? {-}

When we talk about procedures and guidelines, we\'re very much talking about standards and conventions. Standards and conventions allow the products of research to be easily consumed, interpreted, adapted and re-used. For example, the metric system did wonders for standardizing how we measure distances and weight. The chaos that would ensue if every entomologist took specimen measurements with their own system - or determined wing span from different points of origin across the same species!

Standards and conventions allow us to also explore our data and outputs to greater extents than historically possible by allowing us to leverage computers; computers rely on standards to parse and merge data. Without standardization in what and how markers of climate change are recorded, we would be unable to pool the massive amounts of data collected globally to build the understanding that we are for how our climate is changing.

These qualities of standards and conventions - easy consumption, interpretation, adaptation, and re-use - are integral to robust, transparent, reproducible research; qualities that underpin the development of a strong evidence base on which to conduct further research and inform practices and policy.

## Structure {-}

This book is divided into 4 sections.

* File and Data Management
* Data Presentation
* Writing and Citing
* Glossary

**File and data management** covers content related to how to organize, name, and store research data. Broadly speaking, this covers all aspects of research data management.

**Data presentation** covers how data should be presented when summarized or analyzed.

**Writing and citing** touches on tools and approaches to support properly formatted and cited open publications.

**Glossary** is a set of standard definitions for concepts that one will encounter throughout the Biology undergraduate curriculum. When possible, course materials will link directly here.
